#gt968 touchpanel driver


obj-$(CONFIG_GT968_TOUCHPANEL_DRIVER)	+= gt968.o
#gt968 update file
obj-$(CONFIG_GT968_TOUCHPANEL_UPDATE)	+= gt968_update.o
#debug tool
obj-$(CONFIG_GT968_TOUCHPANEL_DEBUG)	+= gt968_tool.o
